<?php

namespace AppBundle\Repository;

/**
 * Example_classRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExampleClassRepository extends \Doctrine\ORM\EntityRepository
{
}
